### ISSUE TITLE
Count number of "wraps" when adding to `ModNum*`

### ISSUE THREAD

**Issue by linclelinkpart5** [gjf2a/bare_metal_modulo#1]
I've found myself in need of a library like this, and it fulfills almost all of my uses! However, I also need to count how many times the modulated value is wrapped around the modulus when performing an addition. For example, if I have `8 mod 17`, and add `42` to it, I'd get the usual `16 mod 17`, along with a `2` to indicate that the modulated value wrapped around the modulus twice.

I'm happy to add this functionality myself and make a PR, but wanted to get feedback beforehand. Namely, I'd love some advice on what to name this method.

**Comment by gjf2a** [comment]
Thank you for your message! It got thrown into my spam folder and I just saw it now.

What you suggest is a really interesting feature. What do you have in mind in terms of the API? Would it be a separate "counting-add" operation? If so, I would be happy to include it in the library.

Thanks for your message and your interest!

**Comment by gjf2a** [comment]
I have thought of a way to implement this. It needs to take into account the original dividend. All operations ultimately funnel down to a call to `.with()`, which will actually perform the modulo. So I think the solution is to introduce a new data type that tracks the total "wraparounds" it has experienced. I just finished a major refactoring of the crate that will facilitate adding new data types.

So, to do this:
* Create a `WrapTrackNum` that keeps track of wrapping and implements the `MNum` trait.
  * It will have a state variable that tracks the total wrap count that occurred when it was created.
* Then invoke the `derive_modulo_arithmetic!` macro to generate all the arithmetic operator implementations.

**Comment by gjf2a** [comment]
Thanks again for the suggestion, @linclelinkpart5! I have now implemented it as follows:
* `WrapCountNum` and `WrapCountNumC` are drop-in replacements for `ModNum` and `ModNumC` that each have a `wraps()` method. 
* That method returns accumulated wraparounds as defined above.
* See the [documentation](https://docs.rs/bare_metal_modulo/1.1.1/bare_metal_modulo/) for a full illustration of how they work.

Due to the delay between this implementation and when you posted the issue, it may or may not be useful to you at this point, but I am guessing that your suggestion indicates something that would be useful to many people, so I am pleased that I was finally able to incorporate it.
